### ISSUE TITLE
Implement TURN relay strategy

### ISSUE THREAD

**Issue by gordonwritescode** [gordonwritescode/kad-traverse#2]
Consider https://github.com/nicojanssens/turn-js

**Comment by nicojanssens** [comment]
PM me if you need a TURN server for testing purposes

**Comment by gordonwritescode** [comment]
Awesome thanks. I'm not sure how to PM on GH, but I should be able to use a public TURN server no?

**Comment by nicojanssens** [comment]
@gordonwritescode Public servers like the Numb STUN/TURN server should also work, as long as they conform to RFC 5389 and RFC 5766.

Using a private TURN server makes debugging a bit easier, that's all.

**Comment by gordonwritescode** [comment]
I tried using Numb, but kept getting back an 'Unknown Attribute' error. I set up a coturn instance on digital ocean and it seems to be working.

**Comment by nicojanssens** [comment]
Thx for the update. Will check this Numb issue.

**Comment by nicojanssens** [comment]
Just checked your turn strategy code.

When sending data to a contact (transport._send), you have to make sure this contact’s socket also executes a createPermission – otherwise your TURN server will drop this data on the floor instead of forwarding it.

There are two ways to fix this.

1) Execute a ‘handshake’ between two sockets (turn-js clients) to make sure all permissions are set before sending data. Disadvantage of this approach is that it requires an additional server to exchange handshake messages between kad nodes.
2) When using coturn, you could also disable those permission checks by using the –server-relay option. Mind that this enters a serious security issue. See coturn manual:

--server-relay Server relay. NON-STANDARD AND DANGEROUS OPTION. Only for an application that want to run a server on the relay endpoints. This option eliminates the IP permissions check on the packets incoming to the relay endpoints. That makes the system vulnerable to DOS attack, for example, among other bad things. The rule is: if you do not understand what is this option about and why would you need it, then you absolutely must NOT use it under any circumstances. See http://tools.ietf.org/search/rfc5766#section-17.2.3 .

**Comment by gordonwritescode** [comment]
Thanks for bringing this up. This poses an interesting problem, since kad nodes have no knowledge of how they have been discovered. When NodeA joins the network, she asks NodeC for contacts closest to her. NodeC responds with 3 contacts, one if which is NodeB. 

Now NodeA can create a permission for NodeB, but NodeB has no knowledge that NodeA wishes to communicate with her and if both are NATed, the communication with fail. 

I don't want to introduce a central server to negotiate handshakes. 

One solution I can think of is to add a hook for every time a contact is added to the router to preemptively create a permission for it. In this case, only nodes that have discovered each other previously through FIND_NODE RPC call can communicate when both are NATed. 

This means that eventually they should be able to establish a connection, but perhaps not the first attempt. I think this might be okay considering that the router will select a different candidate upon timeout. 

Does this sound correct?

**Comment by nicojanssens** [comment]
Sounds OK, definitely worth trying.

**Comment by gordonwritescode** [comment]
This is working, will include some examples soon!

**Comment by nicojanssens** [comment]
Awesome!

Looking forward to test and experiment w this
